#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 10000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o output/%j_%x_%u.out # File to which STDOUT will be written
#SBATCH -e output/%j_%x_%u.err # File to which STDERR will be written
python mlp_MIT_8_scene.py $1
