#!/bin/bash
#SBATCH --array=1-5
#SBATCH -n 4 # Number of cores
#SBATCH --mem 10000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o /home/grupo01/projectF/results/patches_%a/%j_%x_%u.out # File to which STDOUT will be written
#SBATCH -e /home/grupo01/projectF/results/patches_%a/%j_%x_%u.err # File to which STDERR will be written
python patches_test.py  /home/grupo01/projectF/results/patches_${SLURM_ARRAY_TASK_ID}
#python test.py /home/grupo01/projectF/results/patches_${SLURM_ARRAY_TASK_ID}
